### PR TITLE
Official API Implementation

### PR DESCRIPTION
**Pull request by NotCR**
Overall: Implemented the official API

NHentaiURL -> Use the API insted of the HTML pages

BookApi -> Create Books with the Offical API (only used with Random Activity and Direct Galley search)

PageApi -> Properly parse JSON information
PageApi -> Get JSON of multiple books (galleries) or single book

FileCacheMangaer -> Save Book JSON in cache
FileCacheManager -> Minor Bug Fixes (Saving book info in every single image)

FavoritesCacheManager -> Update Category usage

Book -> Added Pretty Title and lists of ids for tags

Category -> Added the id of the tag (Easier API usage)

PageListFragment -> Update URI to match the API

Book Details Activity -> Create Recommended Async Task to download recommended
Book Details Activity -> Added English and Japanese Titles (it looks good)
Book Details Activity -> Align to the new API
Book Details Activity -> Activity Title is now the Pretty Title (Shorter)
Book Details Activity -> Align tags to new API
Book Details Activity -> Manual Image Loading (No more Picasso)

Home Activity -> Align to the new API
HomeActivity -> Save downloaded books to cache

Random Activity -> Align to the new API

Search Activity -> Align to the new API
Search Activity ->Save downloaded books to cache

Activity Book Details -> Added the second text view

Build.Gradle -> Update to Android 24.0.1 build toods
Build.Gradle -> Updated dependencies
Build.Gradle ->Bump to 1.4.0

### CODE REVIEW

**Comment by fython** [comment]
Maybe it's unnecessary to record categories' ids.

**Comment by NotCR** [comment]
When searching with the new API it uses the tag_id, not the tag itself. 
Ex: https://nhentai.net/api/galleries/tagged?tag_id=3735&page=2

We could make custom queries like:
https://nhentai.net/api/galleries/search?query=tags:swimsuit&page=2
But i am trying to save this custom like queries for multi-tag search when we implement it
Should i leave it like that?

Also, if you want to try this version i highly recommend that you erase everything from the old versions, including cache in Android Data and external folder

**Comment by fython** [comment]
Well. Now I agree with you. BTW, may it cause FC if not earsing old caches?

**Comment by NotCR** [comment]
Yeah it can FC. 
I could update the name of the json to force redownloading book info, but to be honest the change deserves a clean install. Making workarounds doesnt sounds good.

What about  a function that runs on first run, that update the old book info and clear caches.
That sounds good? (im still in for the cleanest of the installs)

**Comment by fython** [comment]
> What about a function that runs on first run, that update the old book info and clear caches.

I think we should make this function. Or users will complain it.

Could you help me finish this?

**Comment by NotCR** [comment]
yeah sure, it shouldnt be that hard (I guess)

**Pull request merged**
